### ISSUE TITLE
Python installation broken 3.11

### ISSUE THREAD

**Issue by pbastide** [diyabc/abcranger#96] opened 2024-01-30 14:03 UTC
Hi,

I seem to be having an issue similar to #92, with python `3.11.7`, on a MacOS 14.2.1 with Apple M2.

If I run on a clean terminal:
```
$ python3 -m venv venv-py311
$ source venv-py310/bin/activate
$ python -m pip install -U pip
$ python -m pip install pyabcranger
```
then I get the following error:
```
Collecting pyabcranger
  Using cached pyabcranger-0.0.70.tar.gz (58 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [106 lines of output]
      PYTHON VERSION : 3.11
      running egg_info
      egg_info (cmake)
      writing dist/pyabcranger.egg-info/PKG-INFO
      writing dependency_links to dist/pyabcranger.egg-info/dependency_links.txt
      writing top-level names to dist/pyabcranger.egg-info/top_level.txt
      Cloning into 'ranger'...
      Cloning into 'wingetopt'...
      -- The CXX compiler identification is AppleClang 15.0.0.15000100
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      Compiler ID : AppleClang
      -- The C compiler identification is AppleClang 15.0.0.15000100
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Found Python: /Users/bastidep/ownCloud/Projects/2020_ABC/test_python/venv-py311/bin/python (found version "3.11.7") found components: Interpreter Development.Module
      -- [pmm] Using vcpkg executable: /Users/bastidep/.local/share/pmm/2.1.0/vcpkg-6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2/vcpkg
      CMake Error at build/_pmm/2.1.0/vcpkg.cmake:168 (message):
        Failed find portfile in
        /private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-install-p5t4skm3/pyabcranger_f3d7b0cdc9294be1977616d3e165fe72/pybind11-nodep!
      Call Stack (most recent call first):
        build/_pmm/2.1.0/vcpkg.cmake:224 (_pmm_vcpkg_copy_custom_ports)
        build/_pmm/2.1.0/main.cmake:46 (_pmm_vcpkg)
        build/_pmm/2.1.0/main.cmake:66 (_pmm_project_fn)
        CMakeLists.txt:83 (pmm)
      
      
      -- Configuring incomplete, errors occurred!
      [git] .gitmodules found. Cloning the submodules if necessary
      [git] cloning https://github.com/fradav/ranger.git to ranger...
      [git] cloning complete.
      [git] cloning https://github.com/alex85k/wingetopt.git to wingetopt...
      [git] cloning complete.
      
      [cmake] configuring CMake project...
      
      Traceback (most recent call last):
        File "/Users/bastidep/ownCloud/Projects/2020_ABC/test_python/venv-py311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/bastidep/ownCloud/Projects/2020_ABC/test_python/venv-py311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/bastidep/ownCloud/Projects/2020_ABC/test_python/venv-py311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/cmaketools/__init__.py", line 98, in setup
          _setup(**setup_args)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/cmaketools/cmakecommands.py", line 72, in find_sources
          mm.run()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/cmaketools/cmakecommands.py", line 452, in finalize_options
          self.cmake.configure(self.build_base, **cmake_settings)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/cmaketools/cmakebuilder.py", line 321, in configure
          cmakeutil.configure(".", build_dir, *args, **kwargs)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-938kndll/overlay/lib/python3.11/site-packages/cmaketools/cmakeutil.py", line 120, in configure
          sp.run(args, env=env, check=True).check_returncode()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '.', '-B', 'build', '-DPython_EXECUTABLE=/Users/bastidep/ownCloud/Projects/2020_ABC/test_python/venv-py311/bin/python', '-DPYABCRANGER=TRUE', '-DUSE_MKL:BOOL=FALSE', '-DCMAKE_BUILD_TYPE:STRING=Release', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE:STRING=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Python version is:
```
$ python --version 
Python 3.11.7
```

Am I missing a step, or maybe doing something wrong ?

Thank you for your help and for maintaining this software !

Paul

**Comment by pbastide** [comment] 2024-01-30 14:19
Note : I get the same error if I create a venv environnement with Python `3.10` or `3.9`.

```
$ python --version
Python 3.10.13
$ pip install pyabcranger
Collecting pyabcranger
  Using cached pyabcranger-0.0.70.tar.gz (58 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [99 lines of output]
      PYTHON VERSION : 3.10
      running egg_info
      egg_info (cmake)
      writing dist/pyabcranger.egg-info/PKG-INFO
      writing dependency_links to dist/pyabcranger.egg-info/dependency_links.txt
      writing top-level names to dist/pyabcranger.egg-info/top_level.txt
      Cloning into 'ranger'...
      Cloning into 'wingetopt'...
      -- The CXX compiler identification is AppleClang 15.0.0.15000100
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      Compiler ID : AppleClang
      -- The C compiler identification is AppleClang 15.0.0.15000100
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Found Python: /Users/bastidep/ownCloud/Projects/2020_ABC/sbibm/.venv/bin/python (found version "3.10.13") found components: Interpreter Development.Module
      -- [pmm] Using vcpkg executable: /Users/bastidep/.local/share/pmm/2.1.0/vcpkg-6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2/vcpkg
      CMake Error at build/_pmm/2.1.0/vcpkg.cmake:168 (message):
        Failed find portfile in
        /private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-install-0femsvcd/pyabcranger_560fd0d4bf1b40e4aed0533da941421c/pybind11-nodep!
      Call Stack (most recent call first):
        build/_pmm/2.1.0/vcpkg.cmake:224 (_pmm_vcpkg_copy_custom_ports)
        build/_pmm/2.1.0/main.cmake:46 (_pmm_vcpkg)
        build/_pmm/2.1.0/main.cmake:66 (_pmm_project_fn)
        CMakeLists.txt:83 (pmm)
      
      
      -- Configuring incomplete, errors occurred!
      [git] .gitmodules found. Cloning the submodules if necessary
      [git] cloning https://github.com/fradav/ranger.git to ranger...
      [git] cloning complete.
      [git] cloning https://github.com/alex85k/wingetopt.git to wingetopt...
      [git] cloning complete.
      
      [cmake] configuring CMake project...
      
      Traceback (most recent call last):
        File "/Users/bastidep/ownCloud/Projects/2020_ABC/sbibm/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/bastidep/ownCloud/Projects/2020_ABC/sbibm/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/bastidep/ownCloud/Projects/2020_ABC/sbibm/.venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/cmaketools/__init__.py", line 98, in setup
          _setup(**setup_args)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/cmaketools/cmakecommands.py", line 72, in find_sources
          mm.run()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/cmaketools/cmakecommands.py", line 452, in finalize_options
          self.cmake.configure(self.build_base, **cmake_settings)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/cmaketools/cmakebuilder.py", line 321, in configure
          cmakeutil.configure(".", build_dir, *args, **kwargs)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-ga0zn51u/overlay/lib/python3.10/site-packages/cmaketools/cmakeutil.py", line 120, in configure
          sp.run(args, env=env, check=True).check_returncode()
        File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '.', '-B', 'build', '-DPython_EXECUTABLE=/Users/bastidep/ownCloud/Projects/2020_ABC/sbibm/.venv/bin/python', '-DPYABCRANGER=TRUE', '-DUSE_MKL:BOOL=FALSE', '-DCMAKE_BUILD_TYPE:STRING=Release', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE:STRING=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

```
$ python --version
Python 3.9.6
$ pip install pyabcranger
Collecting pyabcranger
  Using cached pyabcranger-0.0.70.tar.gz (58 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [99 lines of output]
      PYTHON VERSION : 3.9
      running egg_info
      egg_info (cmake)
      writing dist/pyabcranger.egg-info/PKG-INFO
      writing dependency_links to dist/pyabcranger.egg-info/dependency_links.txt
      writing top-level names to dist/pyabcranger.egg-info/top_level.txt
      Cloning into 'ranger'...
      Cloning into 'wingetopt'...
      -- The CXX compiler identification is AppleClang 15.0.0.15000100
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      Compiler ID : AppleClang
      -- The C compiler identification is AppleClang 15.0.0.15000100
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Found Python: /Users/bastidep/ownCloud/Projects/2020_ABC/sbibm/.venv/bin/python (found version "3.9.6") found components: Interpreter Development.Module
      -- [pmm] Using vcpkg executable: /Users/bastidep/.local/share/pmm/2.1.0/vcpkg-6f7ffeb18f99796233b958aaaf14ec7bd4fb64b2/vcpkg
      CMake Error at build/_pmm/2.1.0/vcpkg.cmake:168 (message):
        Failed find portfile in
        /private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-install-q6pbr7k1/pyabcranger_0bcc2049cf894f7984aee912084b066c/pybind11-nodep!
      Call Stack (most recent call first):
        build/_pmm/2.1.0/vcpkg.cmake:224 (_pmm_vcpkg_copy_custom_ports)
        build/_pmm/2.1.0/main.cmake:46 (_pmm_vcpkg)
        build/_pmm/2.1.0/main.cmake:66 (_pmm_project_fn)
        CMakeLists.txt:83 (pmm)
      
      
      -- Configuring incomplete, errors occurred!
      [git] .gitmodules found. Cloning the submodules if necessary
      [git] cloning https://github.com/fradav/ranger.git to ranger...
      [git] cloning complete.
      [git] cloning https://github.com/alex85k/wingetopt.git to wingetopt...
      [git] cloning complete.
      
      [cmake] configuring CMake project...
      
      Traceback (most recent call last):
        File "/Users/bastidep/ownCloud/Projects/2020_ABC/sbibm/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/bastidep/ownCloud/Projects/2020_ABC/sbibm/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/bastidep/ownCloud/Projects/2020_ABC/sbibm/.venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 23, in <module>
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/cmaketools/__init__.py", line 98, in setup
          _setup(**setup_args)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/cmaketools/cmakecommands.py", line 72, in find_sources
          mm.run()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/cmaketools/cmakecommands.py", line 452, in finalize_options
          self.cmake.configure(self.build_base, **cmake_settings)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/cmaketools/cmakebuilder.py", line 321, in configure
          cmakeutil.configure(".", build_dir, *args, **kwargs)
        File "/private/var/folders/h1/pslfk2_93v9g6978_jtrg_3h0000gp/T/pip-build-env-oh3ncw3d/overlay/lib/python3.9/site-packages/cmaketools/cmakeutil.py", line 120, in configure
          sp.run(args, env=env, check=True).check_returncode()
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', '.', '-B', 'build', '-DPython_EXECUTABLE=/Users/bastidep/ownCloud/Projects/2020_ABC/sbibm/.venv/bin/python', '-DPYABCRANGER=TRUE', '-DUSE_MKL:BOOL=FALSE', '-DCMAKE_BUILD_TYPE:STRING=Release', '-G', 'Ninja', '-DCMAKE_BUILD_TYPE:STRING=Release']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by fradav** [comment] 2024-05-07 06:30
duplicate of #101

**Closed by fradav** 2024-05-07 06:30 UTC
